customfpl/antifpl/urls.py
from django.urls import path
from antifpl.views import (
    AntiGWStatsView,
    AntiManagerDetailView,
    AntiPointsTableView,
    AntiPrevGWStatsView,
    AntiPreviousPointsTableView,
    AntiRulesView,
    FootballerDetailView,
)

app_name = "antifpl"

urlpatterns = [
    path("", AntiPointsTableView.as_view(), name="points-table"),
    path(
        "points/<int:pk>/",
        AntiPreviousPointsTableView.as_view(),
        name="prev-points-table",
    ),
    path(
        "manager/<int:pk>/",
        AntiManagerDetailView.as_view(),
        name="manager",
    ),
    path(
        "footballer/<int:pk>/",
        FootballerDetailView.as_view(),
        name="footballer",
    ),
    path("rules/", AntiRulesView.as_view(), name="rules"),
    path("gw-stats/", AntiGWStatsView.as_view(), name="gw-stats"),
    path("gw-stats/<int:pk>/", AntiPrevGWStatsView.as_view(), name="prev-gw-stats"),
]

customfpl/templates/admin_dropdown_filter.html
{% load i18n %}
<script type="text/javascript">var go_from_select = function(opt) { window.location = window.location.pathname + opt };</script>
<h3>{{ title }}</h3>
<ul class="admin-filter-{{ title|cut:' ' }}">
{% if choices|slice:"4:" %}
    <li>
    <select style="width: 95%;"
        onchange="go_from_select(this.options[this.selectedIndex].value)">
    {% for choice in choices %}
        <option{% if choice.selected %} selected="selected"{% endif %}
         value="{{ choice.query_string|iriencode }}">{{ choice.display }}</option>
    {% endfor %}
    </select>
    </li>
{% else %}

    {% for choice in choices %}
            <li{% if choice.selected %} class="selected"{% endif %}>
            <a href="{{ choice.query_string|iriencode }}">{{ choice.display }}</a></li>
    {% endfor %}

{% endif %}
</ul>

customfpl/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
    {% block title %}
    {% endblock title%}
    </title>

    {% block headimport %}
    {% endblock headimport %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" type="text/css">



    <script>
        var isDarkmode = false;
        if (typeof (Storage) !== "undefined" && localStorage.getItem('isDarkmode')) {
            isDarkmode = JSON.parse(localStorage.getItem('isDarkmode'));
        }
        if (isDarkmode === true) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    </script>

    
  </head>
  <body class="dark:bg-gray-900 font-serif ">

    {% include 'navbar.html' %}

    <div class="antialiased min-h-screen  ">
    {% block content %}
    {% endblock content%}
    </div>

    {% include 'footer.html' %} 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> {% endcomment %}
    {% block javascript_end %}
    {% endblock javascript_end %}
    <script>
    // Dark mode enable
    const switchToggle = document.querySelector('#switch-toggle');

    var isDarkmode = false;
    if (typeof (Storage) !== "undefined" && localStorage.getItem('isDarkmode')) {
        isDarkmode = JSON.parse(localStorage.getItem('isDarkmode'));
    }

    const darkIcon = `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
        </svg>`

    const lightIcon = `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
        </svg>`

    function toggleTheme() {
        isDarkmode = !isDarkmode;
        localStorage.setItem('isDarkmode', isDarkmode);
        switchTheme(250);
        setSystemDarkMode();
    }

    function setSystemDarkMode() {
        if (isDarkmode === true) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    }

    function switchTheme(timer) {
        if (isDarkmode === true) {
            switchToggle.classList.remove('bg-yellow-500', '-translate-x-1')
            switchToggle.classList.add('bg-gray-700', 'translate-x-1')
            if (timer === 0) {
                switchToggle.innerHTML = darkIcon

            } else {
                setTimeout(() => {}, timer);
            }

        } else {
            switchToggle.classList.add('bg-yellow-500', '-translate-x-1')
            switchToggle.classList.remove('bg-gray-700', 'translate-x-1')
            setTimeout(() => {
                switchToggle.innerHTML = lightIcon
            }, timer);

        }
    }

    switchTheme(0)
</script>
  </body>
</html>

customfpl/templates/footer.html
<footer class="text-gray-600 dark:text-gray-50 body-font dark:bg-gray-800">
    <div class="container px-5 py-2 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">

            <span class="ml-3 text-xl dark:text-gray-100">Anti FPL 2025/26</span>
        </a>


    </div>
</footer>

customfpl/templates/landing.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Anti FPL
{% endblock title %}


{% block content %}


      
<div class="container mx-auto h-screen px-6 flex items-center justify-between">
  <div class="container mx-auto px-6 flex flex-col-reverse lg:flex-row justify-between items-center relative">
      <div class="w-full  text-center lg:text-left">
          <h1 class="font-light font-sans text-center lg:text-left text-5xl lg:text-8xl mt-2 md:mt-0 text-gray-700">
              Welcome to <span class="font-bold">Anti </span> Fantasy Premier League
          </h1>
          <a href="{% url 'antifpl:points-table' %}">
            <button class="px-2 py-2 w-36 mt-16 font-light transition ease-in duration-200 rounded-lg hover:bg-red-600 border-2 text-lg border-gray-700 bg-red-300 focus:outline-none">
                Points Table
            </button>
          </a>
      </div>
      <div class="block w-full mx-auto md:mt-0 relative max-w-md lg:max-w-2xl opacity-70">
          <img src="{% static 'images/premred.png' %}"/>
      </div>
  </div>
</div>

{% endblock content %}

customfpl/templates/navbar.html
{% load static %}

<nav class="bg-gray-200 dark:bg-gray-800">
  <div class=" mx-xl ">
    <div class="relative flex items-center justify-between h-16">

      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <a href="{% url 'landing-page' %}">
            <img class=" h-16 w-auto" src="{% static 'images/antilogo.png' %}" alt="Anti FPL">
          </a>
        </div>
        
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

        {% comment %} <button
          class="ml-2  h-4 rounded-full bg-white flex items-center transition duration-300 focus:outline-none shadow"
          onclick="toggleTheme()">
          <div id="switch-toggle"
            class="w-6 h-6 relative rounded-full transition duration-500 transform bg-yellow-500 -translate-x-1 p-1 text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
          </div>
        </button> {% endcomment %}

        <div class="ml-3 relative">
          <a href="{% url 'antifpl:points-table' %}"
            class="bg-gray-200 dark:text-gray-300 dark:bg-gray-800 dark:hover:bg-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            Points Table</a>
          <a href="{% url 'antifpl:rules' %}"
            class="bg-gray-200 dark:text-gray-300 dark:bg-gray-800 dark:hover:bg-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            Rules</a>
          <a href="{% url 'antifpl:gw-stats' %}"
            class="bg-gray-200 dark:text-gray-300 dark:bg-gray-800 dark:hover:bg-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            Player Stats</a>
          <a href="#"
            class="bg-gray-200 dark:text-gray-300 dark:bg-gray-800 dark:hover:bg-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            </a>
          
        </div>
      </div>
    </div>
  </div>
</nav>