customfpl/antifpl/urls.py
from django.urls import path
from antifpl.views import (
    AntiGWStatsView,
    AntiManagerDetailView,
    AntiPointsTableView,
    AntiPrevGWStatsView,
    AntiPreviousPointsTableView,
    AntiRulesView,
    FootballerDetailView,
)

app_name = "antifpl"

urlpatterns = [
    path("", AntiPointsTableView.as_view(), name="points-table"),
    path(
        "points/<int:pk>/",
        AntiPreviousPointsTableView.as_view(),
        name="prev-points-table",
    ),
    path(
        "manager/<int:pk>/",
        AntiManagerDetailView.as_view(),
        name="manager",
    ),
    path(
        "footballer/<int:pk>/",
        FootballerDetailView.as_view(),
        name="footballer",
    ),
    path("rules/", AntiRulesView.as_view(), name="rules"),
    path("gw-stats/", AntiGWStatsView.as_view(), name="gw-stats"),
    path("gw-stats/<int:pk>/", AntiPrevGWStatsView.as_view(), name="prev-gw-stats"),
]

customfpl/antifpl/models.py
from django.db import models
import auto_prefetch
from django.utils.translation import ugettext as _
from django.urls import reverse

from fplservice.models import FootballerPerformance

# Create your models here.


class Manager(models.Model):

    team_id = models.IntegerField(_("Team Id"), unique=True, primary_key=True)
    team_name = models.CharField(_("Team Name"), max_length=50)

    manager_id = models.IntegerField(_("Manager Id"), unique=True)
    manager_name = models.CharField(_("Manager Name"), max_length=50)

    class Meta:
        verbose_name = _("Manager")
        verbose_name_plural = _("Managers")

    def __str__(self):
        return f"{self.team_name} - {self.manager_name}"

    def get_absolute_url(self):
        return reverse("Manager_detail", kwargs={"pk": self.pk})


class PointsTable(auto_prefetch.Model):

    manager = auto_prefetch.ForeignKey(
        "antifpl.Manager", verbose_name=_("manager"), on_delete=models.CASCADE
    )
    gw = models.IntegerField(_("Gameweek"))
    team_value = models.IntegerField(_("Team Value"))
    itb = models.IntegerField(_("In the Bank"))
    transfers = models.IntegerField(_("Transfers"))
    transfers_hits = models.IntegerField(_("Transfer Hits"))
    chip = models.CharField(_("Chip"), max_length=10, null=True)
    chip_pen = models.IntegerField(_("Chip Penalty"), blank=True, null=True)
    last_gw = models.IntegerField(_("Last GW Points"))
    site_points = models.IntegerField(_("Site Points"), default=0)
    cvc_pens = models.IntegerField(_("Captain/VC Penalty"), null=True)
    inactive_players = models.IntegerField(_("Inactive Players"), null=True)
    inactive_players_pens = models.IntegerField(
        _("Inactive Players Penalty"), null=True
    )
    gw_points = models.IntegerField(_("GW Points (+Pens)"), default=0)

    rank = models.IntegerField(_("GW Rank"), null=True)
    last_rank = models.IntegerField(_("Last GW Rank"))

    total = models.IntegerField(_("Total"))

    class Meta:
        verbose_name = _("Points Table")
        unique_together = [("manager", "gw")]

    def __str__(self):
        return f"{self.manager.team_name} - {self.gw} - {self.total}"


class FootballerPerformanceAnti(FootballerPerformance):

    anti_points = models.IntegerField(_("Anti Points"), null=True, default=0)

    form_5_gw = models.FloatField(_("Form (5 GW)"), default=0)
    form_season = models.FloatField(_("Form (Season)"), default=0)
    points_per_mil_5_gw = models.FloatField(_("Points Per Million (5 GW)"), default=0)
    points_per_mil_season = models.FloatField(
        _("Points Per Million (Season)"), default=0
    )

    class Meta:
        verbose_name = _("Footballer's Performance Anti")
        verbose_name_plural = _("Footballer Performance Anti")

    def __str__(self):
        return f"{self.footballer} - {self.gw} - {self.anti_points}"

customfpl/antifpl/views.py
from django.shortcuts import render
from django.views import generic
from fplservice.models import Footballer, Gameweek

from antifpl.models import FootballerPerformanceAnti, Manager, PointsTable

from .lib import Antifpl

# Create your views here.


class AntiPointsTableView(generic.View):
    template_name = "antifpl/points_table.html"

    def get(self, request, *args, **kwargs):

        antifpl = Antifpl()
        context_data = {
            "anti_table": antifpl.get_anti_points_table(),
            "gameweeks": Gameweek.objects.filter(completed=True),
            "current_gw": Gameweek.objects.get(id=antifpl.gw),
        }

        return render(request, self.template_name, context_data)


class AntiPreviousPointsTableView(generic.DetailView):
    template_name = "antifpl/points_table.html"

    def get(self, request, *args, **kwargs):
        gw = self.get_object()
        antifpl = Antifpl()
        context_data = {
            "anti_table": PointsTable.objects.filter(gw=gw.id),
            "gameweeks": Gameweek.objects.filter(completed=True),
            "current_gw": gw,
        }

        return render(request, self.template_name, context_data)

    def get_queryset(self):
        return Gameweek.objects.all()


class AntiRulesView(generic.TemplateView):
    template_name = "antifpl/rules.html"


class AntiGWStatsView(generic.View):
    template_name = "antifpl/stats.html"

    def get(self, request, *args, **kwargs):
        antifpl = Antifpl()
        # context_data = {"stats": antifpl.get_footballer_stats()}
        context_data = {
            "player_data": antifpl.get_footballer_stats(),
            "gameweeks": Gameweek.objects.filter(stats_completed=True),
            "current_gw": antifpl.gw,
        }
        return render(request, self.template_name, context_data)


class AntiPrevGWStatsView(generic.DetailView):
    template_name = "antifpl/stats.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        gw = self.get_object()
        context.update(
            {
                "player_data": FootballerPerformanceAnti.objects.filter(gw=gw),
                "gameweeks": Gameweek.objects.filter(stats_completed=True),
                "current_gw": gw.id,
            }
        )
        return context

    def get_queryset(self):
        return Gameweek.objects.all()


class AntiManagerDetailView(generic.DetailView):
    template_name = "antifpl/manager_detail.html"
    context_object_name = "manager"

    def get_queryset(self):
        return Manager.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        manager = self.get_object()

        context.update(
            {"manager_history": PointsTable.objects.filter(manager=manager, gw__gt=0)}
        )
        return context


class FootballerDetailView(generic.DetailView):
    template_name = "antifpl/footballer.html"
    context_object_name = "footballer"

    def get_queryset(self):
        return Footballer.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        footballer = self.get_object()
        context.update(
            {
                "footballer_performance": FootballerPerformanceAnti.objects.filter(
                    footballer=footballer
                )
            }
        )
        return context

customfpl/antifpl/templates/antifpl/manager_detail.html
{% extends "base.html" %}
{% load antifpl_template_filters %}

{% load static %}

{% block title %}
{{ manager.team_name }} - Anti FPL
{% endblock title %}
{% block headimport %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/datatable-all-lib.css' %}"
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    
{% endblock headimport %}


{% block content %}

<div class="container mx-auto pb-2 ">
    <div class="bg-gray-100 dark:bg-gray-900 p-2">
        {% for gw in gameweeks %}
            <div class=" inline-block rounded-full text-white {% if gw.id == current_gw.id  %} bg-blue-400 {% else %} bg-yellow-500 {% endif %} hover:bg-green-500 duration-300 text-xs px-2 opacity-90 hover:opacity-100 cursor-pointer">
                <a href="{% url 'antifpl:prev-points-table' gw.id %}">GW-{{ gw.id }}</a>
            </div>
        {% endfor %}
    </div>
        <h3 class="sm:text-3xl text-2xl text-gray-900 font-medium title-font mb-2">
        {{ manager.team_name }} - {{ manager.manager_name }}
        </h3>  
        <table name="gw-stats" id="gw-stats" class="table table-striped display compact" style="width:100%">
            <thead pt-2 mt-2>
                <tr class="text-left">
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">GW Rank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Last Rank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Gameweek</th>

                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Team Value</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Bank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Transfers</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Transfer Cost</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Chip</th>
                    
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">C/VC Pens</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Inactive Players</th>
                    
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Last GW</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Site Points</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">GW Points (With Pens)</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Total</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs "></th>
                    
                </tr>
            </thead>
            <tbody>
                {% for ptable in manager_history %}
                <tr>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.rank }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.last_rank }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.gw }} (<a href="{% url 'antifpl:prev-points-table' ptable.gw %}" class="text-blue-700 hover:text-blue-500">
                        Table</a>/<a href="{% url 'antifpl:prev-gw-stats' ptable.gw %}" class="text-blue-700 hover:text-blue-500">
                        Stats</a>)</td>

                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.team_value }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.itb }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.transfers|remove_zero }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.transfers_hits|remove_zero }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.chip|default_if_none:"" | safe }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.cvc_pens|remove_zero|default_if_none:"" | safe }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.inactive_players|remove_zero|default_if_none:"" | safe }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.last_gw }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.site_points }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.gw_points }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ ptable.total }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">
                        <a target="_blank" class="text-blue-800 hover:text-blue-500"
                        href="https://fantasy.premierleague.com/entry/{{ manager.team_id }}/event/{{ptable.gw }}/">
                            Team
                        </a>
                        
                    </td>
                    
                    

                </tr>
                {% endfor %}
            </tbody>
        </table>

        

    

</div>
{% endblock content %}

{% block javascript_end %}
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready( function () {
    $('#gw-stats').DataTable({
       "order": [
            [13, "asc"]
        ],
        "pageLength": 40
    });
} );

</script>

{% endblock javascript_end %}

customfpl/antifpl/templates/antifpl/points_table.html
{% extends "base.html" %}
{% load antifpl_template_filters %}

{% load static %}

{% block title %}
Points Table - GW {{ current_gw.id }} - Anti FPL
{% endblock title %}
{% block headimport %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/datatable-all-lib.css' %}"
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    
{% endblock headimport %}


{% block content %}

<div class=" mx-auto pb-2 px-4 ">
    <div class="bg-gray-100 dark:bg-gray-900 p-2">
        {% for gw in gameweeks %}
            <div class=" inline-block rounded-full text-white {% if gw.id == current_gw.id  %} bg-blue-400 {% else %} bg-yellow-500 {% endif %} hover:bg-green-500 duration-300 text-xs px-2 opacity-90 hover:opacity-100 cursor-pointer">
                <a href="{% url 'antifpl:prev-points-table' gw.id %}">GW-{{ gw.id }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="overflow-x-auto bg-white overflow-y-auto relative p-1">
        <h2 class="sm:text-3xl text-2xl text-gray-900 font-medium title-font mb-2">
        Anti Fantasy Points Table - Gameweek {{ current_gw.id }} ({% if current_gw.completed %}Completed{% else %}Live{% endif %})
        </h2>  
        <table name="gw-stats" id="gw-stats" class="table table-striped display compact" style="width:100%">
            <thead pt-2 mt-2>
                <tr class="text-left">
                    <th></th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">GW Rank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Last Rank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Manager</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Team</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Team Value</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Bank</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Transfers</th>
                    {% comment %} <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Hits</th> {% endcomment %}
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Chip</th>
                    {% if current_gw.completed %}
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">C/VC Pens</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Inactive Players</th>
                    {% endif %}
                    {% if current_gw.id == 38 %}
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Chip Penalty</th>
                    {% endif %}
                    
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Last GW</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Site Points</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">GW Points (With Pens)</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Total</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">History</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for manager in anti_table %}
                <tr>
                    <td>
                        {% if manager.rank < manager.last_rank %}
                            <span style="color: green; margin: 0; padding: 0;">&#10506;</span>
                        {% elif manager.rank > manager.last_rank %}
                            <span style="color: red;"> &#10507;</span>
                        {% endif %}
                    </td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.rank }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.last_rank }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm text-blue-900 hover:text-blue-600 ">
                        <a target="_blank"
                        href="https://fantasy.premierleague.com/entry/{{ manager.manager.team_id }}/event/{{ current_gw.id }}">
                            {{ manager.manager.manager_name }}
                        </a>
                    </td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.manager.team_name }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.team_value|normalize_team_value }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm 
                        {% if manager.itb > 30 %} text-red-700 font-bold {% endif %}">
                        {{ manager.itb|normalize_team_value }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.transfers|remove_zero }}
                        {% if manager.transfers_hits > 0 %}
                        ({{ manager.transfers_hits|remove_zero }})
                        {% endif %}
                    </td>
                    {% comment %} <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.transfers_hits|remove_zero }}</td> {% endcomment %}
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.chip|default_if_none:"" | safe }}</td>
                    {% if current_gw.completed %}
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.cvc_pens|remove_zero }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.inactive_players|remove_zero }}</td>
                    {% endif %}
                    {% if current_gw.id == 38 %}
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.chip_pen|remove_zero }}</td>
                    {% endif %}
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.last_gw }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.site_points }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.gw_points }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">{{ manager.total }}</td>
                    <td  class="border-dashed border-t border-gray-200 text-sm ">
                        <a href="{% url 'antifpl:manager' manager.manager.pk %}" class="text-blue-700 hover:text-blue-500">
                        Detail</a>
                    </td>
                    
                    

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
        

    

</div>
{% endblock content %}

{% block javascript_end %}
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready( function () {
    $('#gw-stats').DataTable({
       "order": [
            [1, "asc"]
        ],
        "pageLength": 50
    });
} );

</script>

{% endblock javascript_end %}

customfpl/antifpl/templates/antifpl/stats.html
{% extends "base.html" %}
{% load antifpl_template_filters %}

{% load static %}

{% block title %}
Gameweek Stats - Anti FPL
{% endblock title %}
{% block headimport %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">

{% endblock headimport %}


{% block content %}

<div class="mx-auto pb-2 px-4 ">
    <div class="bg-gray-100 dark:bg-gray-900 p-2">
        {% for gw in gameweeks %}
            <div class=" inline-block rounded-full text-white {% if gw.id == player_data.gw %} bg-blue-400 {% else %} bg-yellow-500 {% endif %} hover:bg-green-500 duration-300 text-xs px-2 opacity-90 hover:opacity-100 cursor-pointer">
                <a href="{% url 'antifpl:prev-gw-stats' gw.id %}">GW-{{ gw.id }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="overflow-x-auto bg-white overflow-y-auto relative p-1">
        <h2 class="sm:text-3xl text-2xl text-gray-900 font-medium title-font mb-2">Player Statistics - Gameweek {{current_gw }}</h2>  
        <table name="gw-stats" id="gw-stats" class="table table-striped display compact" style="width:100%">
            <thead pt-2 mt-2>
                <tr class="text-left">
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Team</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Name</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Cost</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Form (5 GW)</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Form (Season)</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Points Per Million (5 GW)</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Points Per Million (Season)</th>
                    
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Minutes</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Points</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Anti Points</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Starting XI</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Squad</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">Captained</th>
                    <th class="bg-white sticky top-0 border-b border-gray-200 text-gray-600 text-xs ">C/VC</th>
                </tr>
            </thead>
            <tbody>
                {% for player in player_data %}
                <tr>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.team.short_name }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">
                        <a class=" font-bold text-blue-700 hover:text-blue-500" href="{% url 'antifpl:footballer' player.footballer.id %}">
                        {{ player.footballer.name }}
                        </a>
                    </td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.cost|normalize_team_value  }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.form_5_gw }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.form_season }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.points_per_mil_5_gw }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.footballer.points_per_mil_season }}</td>

                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.minutes|default_if_none:"" }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.points|default_if_none:"" }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.anti_points }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.starting_xi }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.squad_xv }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.captains }}</td>
                    <td class="border-dashed border-t border-gray-200 text-sm ">{{ player.cvc }}</td>
                    {% comment %} <td>{{ player.footballer.cvc }}</td> {% endcomment %}
                    

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

        

    

</div>
{% endblock content %}

{% block javascript_end %}
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready( function () {
    $('#gw-stats').DataTable({
    "order": [
                [10, "desc"]
            ],
            "pageLength": 50
    });
} );

</script>

{% endblock javascript_end %}